language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  # for mod_sql_tds
  - sudo apt-get install -y freetds-dev
  # for static code analysis
  - sudo apt-get install -y cppcheck rats
  # for test code coverage
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs cppcheck 2>&1
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs rats --language=c
  - git clone --depth 10 https://github.com/proftpd/proftpd.git
  - cp mod_sql_tds.c proftpd/contrib/
  - cd proftpd
  - ./configure -enable-dso --with-shared=mod_sql:mod_sql_tds
  - make
  - make clean
  - ./configure --with-modules=mod_sql:mod_sql_tds
  - make
